# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml
# There are lots of things you can do with the mods.toml, and not all fields are included with this MDK
# References: https://github.com/MinecraftForge/MDKExamples

modLoader="javafml"
loaderVersion="[61,)"
license="EPL-2.0"
issueTrackerURL="https://github.com/unichat-community/unichat-adapter-minecraft/issues" #optional
#clientSideOnly=true #optional, default=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="UniChat Adapter for Minecraft"
#updateJSONURL="https://example.com/updates.json" #optional
displayURL="https://unichat.voguh.me" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="Voguh" #optional
#displayTest="MATCH_VERSION" #optional, default=MATCH_VERSION when not clientSideOnly, else IGNORE_ALL_VERSION
description='''UniChat Adapter for Minecraft is a mod that allows you to connect your Minecraft to the UniChat platform.'''

[[dependencies.${mod_id}]] #recommended
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,1.22,)"
    ordering="NONE"
    side="BOTH"
