name: Package

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  workflow_call:

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: temurin

defaults:
  run:
    shell: bash

jobs:
  package:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Prepare environment
        uses: ./.github/actions/gradle-setup
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Build mod
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: mod-jars
          path: build/libs/*.jar
